version: '3'

services:
  db:
    image: postgres
    ports:
    - '5432'
    environment:
      - POSTGRES_DB=news_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db