# Generated by Django 3.1.1 on 2020-09-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_auto_20200914_1705"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="story",
            new_name="post",
        ),
    ]
