# Generated by Django 3.1.1 on 2020-09-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_auto_20200914_1712"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="story",
            new_name="post",
        ),
    ]
